name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  IMAGE_NAME: ghstahl/fluffy-waitforport-scratch
  BASE_VERSION: '0.1.0'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Establish Versioning, Tags, and Labels
      id: vtl
      uses: mapped/action-vtl@v0.2.7
      with:
        baseVersion: ${{ env.BASE_VERSION }}
        gitHubToken: ${{ secrets.GITHUB_TOKEN }}
        dockerImage: ${{ env.IMAGE_NAME }}

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Clone wait-for-port
      run: |
        git clone https://github.com/bitnami/wait-for-port.git
    
        
    - name: Build
      run: |
        cd wait-for-port
        go mod download
        go build -v ./...
        ls

    - name: Test
      run: |
        cd wait-for-port
        go test -v ./...

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: .//Dockerfile
        push: ${{ steps.vtl.outputs.docker_push }}
        tags: ${{ steps.vtl.outputs.docker_tags }}
        labels: ${{ steps.vtl.outputs.oci_labels }}
