name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: Clone wait-for-port
      run: |
        git clone https://github.com/bitnami/wait-for-port.git
    
        
    - name: Build
      run: |
        cd wait-for-port
        go mod download
        go build -v ./...
        ls

    - name: Test
      run: |
        cd wait-for-port
        go test -v ./...
